Repository eclipse-zenoh/zenoh-ts, pull requests merged in 2024-12, with the labels that each got.

#56 Ci/all in one
  .github/workflows/release-ts.yml
  .github/workflows/release.yml
Labels: internal

#64 Feat/querier api
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/interface/mod.rs
  zenoh-plugin-remote-api/src/interface/ser_de.rs
  zenoh-plugin-remote-api/src/lib.rs
  zenoh-ts/examples/src/z_querier.ts
  zenoh-ts/src/index.ts
  zenoh-ts/src/liveliness.ts
  zenoh-ts/src/querier.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/querier.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/sample.ts
  zenoh-ts/src/session.ts
Labels: enhancement

#67 readme updated: daemon run instructions added, obsolete info removed
  .gitignore
  Cargo.toml
  EXAMPLE_CONFIG.json5
  README.md
  zenoh-plugin-remote-api/EXAMPLE_CONFIG.json5
Labels: documentation

#68 fix: remove redundant closure
  zenoh-plugin-remote-api/src/handle_control_message.rs
Labels: internal

#72 example chat application which uses zenoh-ts
  .gitignore
  Cargo.toml
  README.md
  package.json
  yarn.lock
  zenoh-ts/examples/chat/README.md
  zenoh-ts/examples/chat/assets/index.css
  zenoh-ts/examples/chat/assets/index.html
  zenoh-ts/examples/chat/package-lock.json
  zenoh-ts/examples/chat/package.json
  zenoh-ts/examples/chat/src/chat_session.ts
  zenoh-ts/examples/chat/src/main.ts
  zenoh-ts/examples/chat/src/validate_keyexpr.ts
  zenoh-ts/examples/chat/tsconfig.json
  zenoh-ts/examples/chat/yarn.lock
  zenoh-ts/examples/deno/README.md
  zenoh-ts/examples/deno/package.json
  zenoh-ts/examples/deno/src/z_delete.ts
  zenoh-ts/examples/deno/src/z_get.ts
  zenoh-ts/examples/deno/src/z_get_liveliness.ts
  zenoh-ts/examples/deno/src/z_liveliness.ts
  zenoh-ts/examples/deno/src/z_ping.ts
  zenoh-ts/examples/deno/src/z_pong.ts
  zenoh-ts/examples/deno/src/z_pub.ts
  zenoh-ts/examples/deno/src/z_put.ts
  zenoh-ts/examples/deno/src/z_querier.ts
  zenoh-ts/examples/deno/src/z_queryable.ts
  zenoh-ts/examples/deno/src/z_sub.ts
  zenoh-ts/examples/deno/src/z_sub_liveliness.ts
  zenoh-ts/examples/deno/src/z_sub_thr.ts
  zenoh-ts/examples/deno/tsconfig.json
  zenoh-ts/examples/deno/yarn.lock
  zenoh-ts/importmap.json
  zenoh-ts/package.json
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/interface/DataMsg.ts
  zenoh-ts/src/remote_api/interface/LivelinessMsg.ts
  zenoh-ts/src/remote_api/interface/QueryReplyVariant.ts
  zenoh-ts/src/remote_api/interface/QueryReplyWS.ts
  zenoh-ts/src/remote_api/interface/QueryWS.ts
  zenoh-ts/src/remote_api/interface/QueryableMsg.ts
  zenoh-ts/src/remote_api/interface/RemoteAPIMsg.ts
  zenoh-ts/src/remote_api/interface/ReplyErrorWS.ts
  zenoh-ts/src/remote_api/interface/ReplyWS.ts
  zenoh-ts/src/remote_api/interface/SampleWS.ts
  zenoh-ts/src/session.ts
  zenoh-ts/tsconfig.json
  zenoh-ts/yarn.lock
Labels: documentation, enhancement

#74 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#76 Add CI for checking markdown format.
  .github/workflows/ci.yml
  .markdownlint.yaml
  README.md
  zenoh-plugin-remote-api/README.md
  zenoh-ts/README.md
  zenoh-ts/examples/chat/README.md
  zenoh-ts/examples/deno/README.md
Labels: internal

#60 Feat/session info
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/interface/mod.rs
  zenoh-ts/.npmrc
  zenoh-ts/examples/deno/src/z_info.ts
  zenoh-ts/src/index.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/interface/DataMsg.ts
  zenoh-ts/src/remote_api/interface/SessionInfo.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/session.ts
Labels: enhancement
