Repository eclipse-zenoh/zenoh-ts, pull requests merged in 2024-11, with the labels that each got.

#10 Add release notes template
  .github/release.yml
Labels: internal

#11 fix: update dev version in config files
  Cargo.lock
  zenoh-plugin-remote-api/Cargo.toml
  zenoh-ts/package.json
Labels: internal

#12 chore: rename workflows to use .yml extension
  .github/workflows/check-labels.yml
  .github/workflows/package-ts.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release-plugin.yml
  .github/workflows/release.yml
Labels: internal

#14 chore: Add Cross.toml file
  Cross.toml
Labels: internal

#15 Feat/add liveliness
  .gitignore
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/interface.rs
  zenoh-plugin-remote-api/src/lib.rs
  zenoh-ts/examples/src/main.ts
  zenoh-ts/examples/src/z_get_liveliness.ts
  zenoh-ts/examples/src/z_liveliness.ts
  zenoh-ts/examples/src/z_sub_liveliness.ts
  zenoh-ts/examples/yarn.lock
  zenoh-ts/package.json
  zenoh-ts/src/index.ts
  zenoh-ts/src/liveliness.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/interface/LivelinessMsg.ts
  zenoh-ts/src/remote_api/pubsub.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/session.ts
  zenoh-ts/yarn.lock
Labels: enhancement

#20 fix: exclude unsupported targets
  .github/workflows/release.yml
Labels: internal

#19 fix: adjust zenoh-plugin-remote-api LICENSE path
  zenoh-plugin-remote-api/Cargo.toml
Labels: internal

#24 fix: correct how exclude-builds is passed
  .github/workflows/release.yml
Labels: internal

#25 chore: fix exclude-builds pattern
  .github/workflows/release.yml
Labels: internal

#26 chore: enable publish workflows
  .github/workflows/release.yml
Labels: internal

#27 fix: remove release crate job
  .github/workflows/release.yml
Labels: internal

#22 Feat/add deno support + fix Liveliness drop
  zenoh-plugin-remote-api/src/lib.rs
  zenoh-ts/README.md
  zenoh-ts/examples/README.md
  zenoh-ts/examples/index.html
  zenoh-ts/examples/package-lock.json
  zenoh-ts/examples/package.json
  zenoh-ts/examples/public/vite.svg
  zenoh-ts/examples/src/main.ts
  zenoh-ts/examples/src/style.css
  zenoh-ts/examples/src/typescript.svg
  zenoh-ts/examples/src/vite-env.d.ts
  zenoh-ts/examples/src/webpage.ts
  zenoh-ts/examples/src/z_delete.ts
  zenoh-ts/examples/src/z_get.ts
  zenoh-ts/examples/src/z_get_liveliness.ts
  zenoh-ts/examples/src/z_liveliness.ts
  zenoh-ts/examples/src/z_ping.ts
  zenoh-ts/examples/src/z_pong.ts
  zenoh-ts/examples/src/z_pub.ts
  zenoh-ts/examples/src/z_put.ts
  zenoh-ts/examples/src/z_queryable.ts
  zenoh-ts/examples/src/z_sub.ts
  zenoh-ts/examples/src/z_sub_liveliness.ts
  zenoh-ts/examples/src/z_sub_thr.ts
  zenoh-ts/examples/vite.config.js
  zenoh-ts/examples/yarn.lock
  zenoh-ts/src/index.ts
  zenoh-ts/src/liveliness.ts
  zenoh-ts/src/pubsub.ts
  zenoh-ts/src/query.ts
  zenoh-ts/src/remote_api/pubsub.ts
  zenoh-ts/src/remote_api/query.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/sample.ts
  zenoh-ts/src/session.ts
Labels: enhancement

#32 bump version 1.0.2-dev
  zenoh-ts/package.json
Labels: internal

#31 Run Publish Docs on workflow dispatch
  .github/workflows/publish-docs.yml
Labels: documentation

#29 feat: add musl build support
  .cargo/config.toml
  .github/workflows/release.yml
Labels: internal

#38 Fix/queryable ts plugin
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/handle_data_message.rs
  zenoh-plugin-remote-api/src/interface.rs
  zenoh-plugin-remote-api/src/lib.rs
  zenoh-ts/examples/src/z_get.ts
  zenoh-ts/examples/src/z_queryable.ts
  zenoh-ts/examples/src/z_sub.ts
  zenoh-ts/src/query.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/sample.ts
  zenoh-ts/src/session.ts
Labels: enhancement

#34 ci/rework-include-ts
  .github/workflows/publish-docs.yml
  .github/workflows/release-plugin.yml
  .github/workflows/release-ts.yml
  .github/workflows/release.yml
  ci/scripts/bump-and-tag.bash
Labels: internal

#41 fix: align bump and tag with other projects
  ci/scripts/bump-and-tag.bash
Labels: internal

#43 update workspace.package.version, not creating package at top level
  ci/scripts/bump-and-tag.bash
Labels: internal

#44 Add bumping of internal deps for plugin
  .github/workflows/release.yml
  ci/scripts/bump-and-tag.bash
Labels: internal

#45 Commit change to Cargo.toml
  ci/scripts/bump-and-tag.bash
Labels: internal

#46 Fix Category slugs, crates.io
  .github/workflows/release.yml
  Cargo.toml
  zenoh-plugin-remote-api/Cargo.toml
Labels: internal

#51 Fix panic if WS handshake fails at runtime
  zenoh-plugin-remote-api/src/lib.rs
Labels: internal

#50 Ci/npm release admin
  zenoh-ts/.npmrc
  zenoh-ts/examples/package.json
  zenoh-ts/package.json
Labels: internal
