Repository eclipse-zenoh/zenoh-ts, pull requests merged in 2025-01, with the labels that each got.

#73 Align async, remove unneccsary Async/Promise
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/handle_data_message.rs
  zenoh-plugin-remote-api/src/interface/mod.rs
  zenoh-plugin-remote-api/src/lib.rs
  zenoh-ts/examples/deno/README.md
  zenoh-ts/examples/deno/deno.lock
  zenoh-ts/examples/deno/src/z_delete.ts
  zenoh-ts/examples/deno/src/z_get.ts
  zenoh-ts/examples/deno/src/z_get_liveliness.ts
  zenoh-ts/examples/deno/src/z_info.ts
  zenoh-ts/examples/deno/src/z_liveliness.ts
  zenoh-ts/examples/deno/src/z_ping.ts
  zenoh-ts/examples/deno/src/z_pong.ts
  zenoh-ts/examples/deno/src/z_pub.ts
  zenoh-ts/examples/deno/src/z_put.ts
  zenoh-ts/examples/deno/src/z_querier.ts
  zenoh-ts/examples/deno/src/z_queryable.ts
  zenoh-ts/examples/deno/src/z_sub.ts
  zenoh-ts/examples/deno/src/z_sub_liveliness.ts
  zenoh-ts/examples/deno/src/z_sub_thr.ts
  zenoh-ts/src/key_expr.ts
  zenoh-ts/src/liveliness.ts
  zenoh-ts/src/pubsub.ts
  zenoh-ts/src/querier.ts
  zenoh-ts/src/query.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/interface/DataMsg.ts
  zenoh-ts/src/remote_api/pubsub.ts
  zenoh-ts/src/remote_api/querier.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/sample.ts
  zenoh-ts/src/session.ts
  zenoh-ts/src/timestamp.ts
  zenoh-ts/src/z_bytes.ts
Labels: enhancement

#86 remove unused KeyExpr field in state map
  zenoh-plugin-remote-api/src/lib.rs
Labels: enhancement

#91 Added keyexpr API using wasm module
  .gitignore
  Cargo.lock
  Cargo.toml
  zenoh-keyexpr-wasm/Cargo.toml
  zenoh-keyexpr-wasm/README.md
  zenoh-keyexpr-wasm/src/lib.rs
  zenoh-ts/package.json
  zenoh-ts/src/key_expr.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper.d.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper.js
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.js
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm.d.ts
  zenoh-ts/tsconfig.json
Labels: enhancement, internal

#89 corrected API to make it similar to C++ which have the closest logic
  zenoh-ts/examples/chat/src/chat_session.ts
  zenoh-ts/examples/deno/src/z_ping.ts
  zenoh-ts/examples/deno/src/z_pong.ts
  zenoh-ts/examples/deno/src/z_pub.ts
  zenoh-ts/examples/deno/src/z_querier.ts
  zenoh-ts/examples/deno/src/z_sub.ts
  zenoh-ts/examples/deno/src/z_sub_thr.ts
  zenoh-ts/src/pubsub.ts
  zenoh-ts/src/querier.ts
  zenoh-ts/src/session.ts
Labels: bug

#92 Fix clippy warning
  zenoh-keyexpr-wasm/src/lib.rs
Labels: internal

#93 documentation to keyexpr module added
  zenoh-ts/src/key_expr.ts
Labels: documentation

#95 comment out Wasm until bundling fix
  zenoh-ts/src/key_expr.ts
Labels: internal

#97 dont publish keyexpr wrapper
  zenoh-keyexpr-wasm/Cargo.toml
Labels: internal

#103 keyexpr API with wasm restored
  Cargo.toml
  README.md
  package.json
  zenoh-keyexpr-wasm/Cargo.toml
  zenoh-keyexpr-wasm/rust-toolchain.toml
  zenoh-ts/README.md
  zenoh-ts/examples/chat/README.md
  zenoh-ts/examples/chat/assets/index.html
  zenoh-ts/examples/chat/package.json
  zenoh-ts/examples/chat/src/chat_session.ts
  zenoh-ts/examples/chat/src/main.ts
  zenoh-ts/examples/chat/src/validate_keyexpr.ts
  zenoh-ts/examples/chat/tsconfig.json
  zenoh-ts/examples/chat/webpack.config.js
  zenoh-ts/examples/chat/yarn.lock
  zenoh-ts/examples/deno/README.md
  zenoh-ts/examples/deno/package.json
  zenoh-ts/package.json
  zenoh-ts/src/key_expr.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper.d.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper.js
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.js
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm.d.ts
Labels: enhancement

#106 parameter parsing improved for examples
  zenoh-keyexpr-wasm/src/lib.rs
  zenoh-ts/examples/deno/package.json
  zenoh-ts/examples/deno/src/parse_args.ts
  zenoh-ts/examples/deno/src/z_delete.ts
  zenoh-ts/examples/deno/src/z_get.ts
  zenoh-ts/examples/deno/src/z_get_liveliness.ts
  zenoh-ts/examples/deno/src/z_liveliness.ts
  zenoh-ts/examples/deno/src/z_pub.ts
  zenoh-ts/examples/deno/src/z_put.ts
  zenoh-ts/examples/deno/src/z_querier.ts
  zenoh-ts/examples/deno/src/z_queryable.ts
  zenoh-ts/examples/deno/src/z_sub.ts
  zenoh-ts/examples/deno/src/z_sub_liveliness.ts
  zenoh-ts/package.json
  zenoh-ts/src/key_expr.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper.d.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.js
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm.d.ts
Labels: enhancement

#109 corrected branch references to fix loading plugin crash
  Cargo.lock
  Cargo.toml
  zenoh-keyexpr-wasm/Cargo.toml
Labels: internal

#107 Final api polish
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/interface/mod.rs
  zenoh-ts/src/encoding.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm
  zenoh-ts/src/pubsub.ts
  zenoh-ts/src/querier.ts
  zenoh-ts/src/query.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/querier.ts
  zenoh-ts/src/sample.ts
  zenoh-ts/src/session.ts
Labels: enhancement

#110 Final api polish 2
  README.md
  zenoh-plugin-remote-api/src/handle_data_message.rs
  zenoh-plugin-remote-api/src/interface/mod.rs
  zenoh-ts/examples/chat/src/chat_session.ts
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm
  zenoh-ts/src/pubsub.ts
  zenoh-ts/src/query.ts
  zenoh-ts/src/remote_api/interface/QueryReplyVariant.ts
  zenoh-ts/src/session.ts
Labels: enhancement

#111 API alignment: handler is always in options
  README.md
  zenoh-ts/examples/chat/src/chat_session.ts
  zenoh-ts/examples/deno/src/z_ping.ts
  zenoh-ts/examples/deno/src/z_pong.ts
  zenoh-ts/examples/deno/src/z_sub.ts
  zenoh-ts/examples/deno/src/z_sub_thr.ts
  zenoh-ts/src/liveliness.ts
  zenoh-ts/src/session.ts
Labels: enhancement
