Repository eclipse-zenoh/zenoh-ts, pull requests merged in 2025-05, with the labels that each got.

#209 `Parameters` treated as string as in Rust, API corrected to match Rust one
  zenoh-ts/src/query.ts
  zenoh-ts/tests/src/z_api_queryable_get.ts
  zenoh-ts/tests/src/z_keyexpr.ts
  zenoh-ts/tests/src/z_parameters.ts
Labels: enhancement

#216 use zenoh serialization in browser example, fixed several issues in serialization
  .github/workflows/ci.yml
  Cargo.lock
  README.md
  zenoh-ts/examples/browser/chat/package-lock.json
  zenoh-ts/examples/browser/chat/package.json
  zenoh-ts/examples/browser/chat/src/chat_session.ts
  zenoh-ts/examples/browser/chat/src/main.ts
  zenoh-ts/examples/browser/chat/webpack.config.js
  zenoh-ts/examples/browser/chat/yarn.lock
  zenoh-ts/examples/deno/scripts/start.sh
  zenoh-ts/examples/deno/tsconfig.json
  zenoh-ts/scripts/start.sh
  zenoh-ts/src/ext/serialization.ts
  zenoh-ts/tests/scripts/start.sh
  zenoh-ts/tests/src/z_parameters.ts
  zenoh-ts/tests/src/z_serialization.ts
Labels: bug, enhancement

#217 remove unused text-encoding module
  .github/workflows/ci.yml
  zenoh-ts/examples/browser/chat/yarn.lock
  zenoh-ts/examples/deno/yarn.lock
  zenoh-ts/package.json
  zenoh-ts/scripts/build.sh
  zenoh-ts/tests/yarn.lock
  zenoh-ts/yarn.lock
Labels: internal

#218 ci: add step to setup deno
  .github/workflows/release.yml
Labels: internal

#222 use deno's test framework for testing, analyze test coverage
  .gitignore
  deno.lock
  zenoh-ts/examples/deno/deno.json
  zenoh-ts/scripts/build.sh
  zenoh-ts/scripts/start.sh
  zenoh-ts/tests/deno.lock
  zenoh-ts/tests/scripts/start.sh
  zenoh-ts/tests/src/common/assertions.ts
  zenoh-ts/tests/src/z_api_pub_sub.ts
  zenoh-ts/tests/src/z_api_queryable_get.ts
  zenoh-ts/tests/src/z_channels.ts
  zenoh-ts/tests/src/z_keyexpr.ts
  zenoh-ts/tests/src/z_liveliness.ts
  zenoh-ts/tests/src/z_parameters.ts
  zenoh-ts/tests/src/z_serialization.ts
Labels: internal

#230 Encoding.withSchema behaviour made the same as in other implementations
  zenoh-ts/scripts/start.sh
  zenoh-ts/src/encoding.ts
  zenoh-ts/tests/src/z_encoding.ts
Labels: enhancement
