Repository eclipse-zenoh/zenoh-ts, pull requests merged in 2025-06, with the labels that each got.

#236 Binary format
  Cargo.lock
  Cargo.toml
  zenoh-plugin-remote-api/Cargo.toml
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-plugin-remote-api/src/handle_data_message.rs
  zenoh-plugin-remote-api/src/interface/mod.rs
  zenoh-plugin-remote-api/src/interface/ser_de.rs
  zenoh-plugin-remote-api/src/lib.rs
  zenoh-plugin-remote-api/src/remote_state.rs
  zenoh-ts/examples/browser/chat/src/chat_session.ts
  zenoh-ts/examples/deno/src/z_get.ts
  zenoh-ts/examples/deno/src/z_get_liveliness.ts
  zenoh-ts/examples/deno/src/z_info.ts
  zenoh-ts/examples/deno/src/z_pub.ts
  zenoh-ts/examples/deno/src/z_pub_thr.ts
  zenoh-ts/examples/deno/src/z_querier.ts
  zenoh-ts/examples/deno/src/z_queryable.ts
  zenoh-ts/examples/deno/src/z_sub.ts
  zenoh-ts/examples/deno/src/z_sub_thr.ts
  zenoh-ts/src/channels.ts
  zenoh-ts/src/closure.ts
  zenoh-ts/src/config.ts
  zenoh-ts/src/encoding.ts
  zenoh-ts/src/enums.ts
  zenoh-ts/src/ext/serialization.ts
  zenoh-ts/src/index.ts
  zenoh-ts/src/key_expr.ts
  zenoh-ts/src/link.ts
  zenoh-ts/src/liveliness.ts
  zenoh-ts/src/message.ts
  zenoh-ts/src/pubsub.ts
  zenoh-ts/src/querier.ts
  zenoh-ts/src/query.ts
  zenoh-ts/src/remote_api/interface/B64String.ts
  zenoh-ts/src/remote_api/interface/ControlMsg.ts
  zenoh-ts/src/remote_api/interface/DataMsg.ts
  zenoh-ts/src/remote_api/interface/LivelinessMsg.ts
  zenoh-ts/src/remote_api/interface/OwnedKeyExprWrapper.ts
  zenoh-ts/src/remote_api/interface/QueryReplyVariant.ts
  zenoh-ts/src/remote_api/interface/QueryReplyWS.ts
  zenoh-ts/src/remote_api/interface/QueryWS.ts
  zenoh-ts/src/remote_api/interface/QueryableMsg.ts
  zenoh-ts/src/remote_api/interface/RemoteAPIMsg.ts
  zenoh-ts/src/remote_api/interface/ReplyErrorWS.ts
  zenoh-ts/src/remote_api/interface/ReplyWS.ts
  zenoh-ts/src/remote_api/interface/SampleKindWS.ts
  zenoh-ts/src/remote_api/interface/SampleWS.ts
  zenoh-ts/src/remote_api/interface/SessionInfo.ts
  zenoh-ts/src/remote_api/pubsub.ts
  zenoh-ts/src/remote_api/querier.ts
  zenoh-ts/src/remote_api/query.ts
  zenoh-ts/src/remote_api/session.ts
  zenoh-ts/src/sample.ts
  zenoh-ts/src/session.ts
  zenoh-ts/src/session_inner.ts
  zenoh-ts/src/timestamp.ts
  zenoh-ts/src/z_bytes.ts
  zenoh-ts/src/zid.ts
  zenoh-ts/tests/src/z_api_queryable_get.ts
Labels: bug, enhancement

#242 correction to Timestamp API: use number for getMsSinceUnixEpoch return type
  zenoh-ts/src/message.ts
  zenoh-ts/src/timestamp.ts
  zenoh-ts/tests/src/z_timestamp.ts
Labels: enhancement

#243 yarn build script builds library by default
  README.md
  zenoh-ts/scripts/build.sh
Labels: internal

#255 ci: update bump and tag deps pattern
  .github/workflows/release.yml
Labels: internal

#256 ci: bump zenoh-plugin-remote-api in bump-and-tag
  .github/workflows/release.yml
  ci/scripts/bump-and-tag.bash
Labels: internal

#257 Nuxt example
  .github/workflows/ci.yml
  README.md
  zenoh-ts/deno.lock
  zenoh-ts/eslint.config.cjs
  zenoh-ts/examples/browser/nuxt/.eslintrc.js
  zenoh-ts/examples/browser/nuxt/.gitignore
  zenoh-ts/examples/browser/nuxt/app.vue
  zenoh-ts/examples/browser/nuxt/assets/css/shared.css
  zenoh-ts/examples/browser/nuxt/components/AcceptRepliesSelect.vue
  zenoh-ts/examples/browser/nuxt/components/AllowedDestinationSelect.vue
  zenoh-ts/examples/browser/nuxt/components/CheckBox.vue
  zenoh-ts/examples/browser/nuxt/components/CheckButton.vue
  zenoh-ts/examples/browser/nuxt/components/ClientOnly.vue
  zenoh-ts/examples/browser/nuxt/components/CongestionControlSelect.vue
  zenoh-ts/examples/browser/nuxt/components/ConsolidationSelect.vue
  zenoh-ts/examples/browser/nuxt/components/EncodingSelect.vue
  zenoh-ts/examples/browser/nuxt/components/Entity.vue
  zenoh-ts/examples/browser/nuxt/components/ExpressSelect.vue
  zenoh-ts/examples/browser/nuxt/components/KeyExprInput.vue
  zenoh-ts/examples/browser/nuxt/components/NumberOptionSelect.vue
  zenoh-ts/examples/browser/nuxt/components/ParameterDisplay.vue
  zenoh-ts/examples/browser/nuxt/components/PayloadInput.vue
  zenoh-ts/examples/browser/nuxt/components/PrioritySelect.vue
  zenoh-ts/examples/browser/nuxt/components/ReliabilitySelect.vue
  zenoh-ts/examples/browser/nuxt/components/ResponseTypeSelect.vue
  zenoh-ts/examples/browser/nuxt/components/Section.vue
  zenoh-ts/examples/browser/nuxt/components/ServerInput.vue
  zenoh-ts/examples/browser/nuxt/components/TargetSelect.vue
  zenoh-ts/examples/browser/nuxt/components/ThemeSelector.vue
  zenoh-ts/examples/browser/nuxt/components/TimeoutInput.vue
  zenoh-ts/examples/browser/nuxt/components/TriStateCheckbox.vue
  zenoh-ts/examples/browser/nuxt/composables/useTheme.ts
  zenoh-ts/examples/browser/nuxt/composables/useZenohDemo.ts
  zenoh-ts/examples/browser/nuxt/composables/zenohDemo/safeUtils.ts
  zenoh-ts/examples/browser/nuxt/composables/zenohDemo/zenohDemo.ts
  zenoh-ts/examples/browser/nuxt/composables/zenohDemo/zenohUtils.ts
  zenoh-ts/examples/browser/nuxt/nuxt.config.ts
  zenoh-ts/examples/browser/nuxt/package-lock.json
  zenoh-ts/examples/browser/nuxt/package.json
  zenoh-ts/examples/browser/nuxt/public/favicon.ico
  zenoh-ts/examples/browser/nuxt/public/robots.txt
  zenoh-ts/examples/browser/nuxt/public/themes/boxed.css
  zenoh-ts/examples/browser/nuxt/public/themes/flat.css
  zenoh-ts/examples/browser/nuxt/public/themes/none.css
  zenoh-ts/examples/browser/nuxt/server/tsconfig.json
  zenoh-ts/examples/browser/nuxt/tsconfig.json
  zenoh-ts/examples/browser/nuxt/yarn.lock
  zenoh-ts/package.json
  zenoh-ts/scripts/build.sh
  zenoh-ts/scripts/clean.sh
  zenoh-ts/scripts/start.sh
  zenoh-ts/src/index.ts
  zenoh-ts/src/session.ts
  zenoh-ts/tests/src/z_queryable_get_options.ts
Labels: bug, enhancement
