Repository eclipse-zenoh/zenoh-ts, pull requests merged in 2025-03, with the labels that each got.

#144 added legal files, same as main zenoh repo
  CONTRIBUTING.md
  LICENSE
  NOTICE.md
Labels: documentation

#147 remove channel upon undeclaration of Subscriber and Queryable
  zenoh-plugin-remote-api/src/handle_control_message.rs
  zenoh-ts/src/key_expr/zenoh_keyexpr_wrapper_bg.wasm
  zenoh-ts/src/remote_api/pubsub.ts
  zenoh-ts/src/remote_api/query.ts
  zenoh-ts/src/remote_api/session.ts
Labels: internal

#145 Bump Rust toolchain to 1.85
  rust-toolchain.toml
  zenoh-plugin-remote-api/src/config.rs
Labels: internal

#160 fix: add rust 1.75 CI check
  .github/workflows/ci.yml
Labels: internal

#166 chore: update workspace.metadata.bin
  Cargo.toml
Labels: internal

#173 fixed crash on session info request due to tokio version mismatch
  Cargo.lock
  Cargo.toml
Labels: bug
